CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(50)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(30)		NOT NULL,
	"MEMBER_NM"	VARCHAR2(20)		NOT NULL,
	"MEMBER_GENDER"	CHAR(1)		NOT NULL,
	"MEMBER_BIRTH"	DATE		NOT NULL,
	"MEMBER_PHONE"	VARCHAR2(20)		NOT NULL,
	"MEMBER_NICK"	VARCHAR2(20)		NOT NULL,
	"SECESSION_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"PROFILE_IMG"	VARCHAR2(500)		NULL,
	"MEMBER_LIVE"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호(시퀀스)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 이메일(아이디)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NM" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_GENDER" IS '회원 성별';

COMMENT ON COLUMN "MEMBER"."MEMBER_BIRTH" IS '회원 생년월일';

COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS '회원 휴대폰번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICK" IS '회원 닉네임';

COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '탈퇴여부(Y:탈퇴, N:미탈퇴)';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '회원 프로필 이미지';

COMMENT ON COLUMN "MEMBER"."MEMBER_LIVE" IS '회원 지역';

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(150)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_ST"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BOARD_CD"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"COMMUNITY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."CREATE_DT" IS '작성일';

COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_ST" IS '게시글 상태(정상N, 삭제Y)';

COMMENT ON COLUMN "BOARD"."BOARD_CD" IS '게시판 코드';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '게시글 작성자';

COMMENT ON COLUMN "BOARD"."COMMUNITY_NO" IS '모임 번호';

CREATE TABLE "COMMUNITY" (
	"COMMUNITY_NO"	NUMBER		NOT NULL,
	"COMMUNITY_NM"	VARCHAR2(50)		NOT NULL,
	"COMMUNITY_IMG"	VARCHAR2(500)		NOT NULL,
	"COMMUNITY_INFO"	VARCHAR2(1000)		NOT NULL,
	"COMMUNITY_DETAIL"	VARCHAR2(4000)		NOT NULL,
	"COMMUNITY_AREA"	VARCHAR2(200)		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"COMMUNITY_ADMIN"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"COMMUNITY_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"COMMUNITY_NOTICE"	VARCHAR2(4000)		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_NO" IS '모임 번호';

COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_NM" IS '모임명';

COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_IMG" IS '모임 이미지';

COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_INFO" IS '모임소개';

COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_DETAIL" IS '상세정보';

COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_AREA" IS '모임 지역';

COMMENT ON COLUMN "COMMUNITY"."MEMBER_NO" IS '회원 번호(시퀀스)';

COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_ADMIN" IS '모임장여부(Y:모임장, N:일반회원)';

COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_FL" IS '모임 상태(Y:모임삭제, N:모임유지)';

COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_NOTICE" IS '모임 내 공지사항';

COMMENT ON COLUMN "COMMUNITY"."CATEGORY_NO" IS '카테고리 번호';

CREATE TABLE "BOARD_TYPE" (
	"BOARD_CD"	NUMBER		NOT NULL,
	"BOARD_NM"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CD" IS '게시판 코드';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NM" IS '게시판 이름';

CREATE TABLE "BOARD_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"IMG_LEVEL"	NUMBER		NOT NULL,
	"IMG_NM"	VARCHAR2(500)		NOT NULL,
	"IMG_ORIGINAL"	VARCHAR2(500)		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_IMG"."IMG_NO" IS '이미지 번호';

COMMENT ON COLUMN "BOARD_IMG"."IMG_LEVEL" IS '이미지 위치';

COMMENT ON COLUMN "BOARD_IMG"."IMG_NM" IS '이미지 이름';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORIGINAL" IS '이미지 원본명';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '게시글 번호';

CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER		NOT NULL,
	"REPLY_CONTENT"	VARCHAR2(2000)		NOT NULL,
	"REPLY_ST"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REPLY"."REPLY_NO" IS '댓글 번호';

COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "REPLY"."REPLY_ST" IS '댓글 상태(정상N, 삭제Y)';

COMMENT ON COLUMN "REPLY"."CREATE_DT" IS '댓글 작성일';

COMMENT ON COLUMN "REPLY"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "REPLY"."MEMBER_NO" IS '댓글 작성자';

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REPORT_TITLE"	VARCHAR2(100)		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_NO2"	NUMBER		NULL,
	"COMMUNITY_NO"	NUMBER		NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고번호';

COMMENT ON COLUMN "REPORT"."REPORT_DATE" IS '신고일';

COMMENT ON COLUMN "REPORT"."REPORT_TITLE" IS '신고사유';

COMMENT ON COLUMN "REPORT"."MEMBER_NO" IS '신고한 회원번호';

COMMENT ON COLUMN "REPORT"."MEMBER_NO2" IS '신고받은 회원번호';

COMMENT ON COLUMN "REPORT"."COMMUNITY_NO" IS '신고받은 모임번호';

CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER		NOT NULL,
	"NOTICE_CD"	NUMBER		NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(150)		NOT NULL,
	"NOTICE_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"NOTICE_ST"	CHAR(1)	DEFAULT N	NOT NULL,
	"MEMBER_NO"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '공지사항 번호';

COMMENT ON COLUMN "NOTICE"."NOTICE_CD" IS '공지사항 코드';

COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS '공지사항 제목';

COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '공지사항 내용';

COMMENT ON COLUMN "NOTICE"."CREATE_DT" IS '작성일';

COMMENT ON COLUMN "NOTICE"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "NOTICE"."NOTICE_ST" IS '공지사항 상태(정상N, 삭제Y)';

COMMENT ON COLUMN "NOTICE"."MEMBER_NO" IS '관리자(0)';

CREATE TABLE "PICK" (
	"COMMUNITY_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PICK"."COMMUNITY_NO" IS '모임 번호';

COMMENT ON COLUMN "PICK"."MEMBER_NO" IS '회원 번호(시퀀스)';

CREATE TABLE "NOTICE_TYPE" (
	"NOTICE_CD"	NUMBER		NOT NULL,
	"NOTICE_NM"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "NOTICE_TYPE"."NOTICE_CD" IS '공지사항 코드';

COMMENT ON COLUMN "NOTICE_TYPE"."NOTICE_NM" IS '공지사항 이름';

CREATE TABLE "NOTICE_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"IMG_LEVEL"	NUMBER		NOT NULL,
	"IMG_NM"	VARCHAR2(500)		NOT NULL,
	"IMG_ORIGINAL"	VARCHAR2(500)		NOT NULL,
	"NOTICE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "NOTICE_IMG"."IMG_NO" IS '이미지 번호';

COMMENT ON COLUMN "NOTICE_IMG"."IMG_LEVEL" IS '이미지 위치';

COMMENT ON COLUMN "NOTICE_IMG"."IMG_NM" IS '이미지 이름';

COMMENT ON COLUMN "NOTICE_IMG"."IMG_ORIGINAL" IS '이미지 원본명';

COMMENT ON COLUMN "NOTICE_IMG"."NOTICE_NO" IS '공지사항 번호';

CREATE TABLE "COMMUNITY_MEMBER" (
	"COMMUNITY_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_COUNT"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "COMMUNITY_MEMBER"."COMMUNITY_NO" IS '모임 번호';

COMMENT ON COLUMN "COMMUNITY_MEMBER"."MEMBER_NO" IS '회원 번호(시퀀스)';

COMMENT ON COLUMN "COMMUNITY_MEMBER"."MEMBER_FL" IS '모임 탈퇴여부((Y:탈퇴, N:미탈퇴)';

COMMENT ON COLUMN "COMMUNITY_MEMBER"."MEMBER_COUNT" IS '모임 회원 수';

CREATE TABLE "PICK_CATEGORY" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PICK_CATEGORY"."MEMBER_NO" IS '회원 번호(시퀀스)';

COMMENT ON COLUMN "PICK_CATEGORY"."CATEGORY_NO" IS '카테고리 번호';

CREATE TABLE "CATEGORY" (
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"CATEGORY_NM"	VARCHAR2(50)		NOT NULL,
	"CATEGORY_IMG"	VARCHAR2(500)		NOT NULL
);

COMMENT ON COLUMN "CATEGORY"."CATEGORY_NO" IS '카테고리 번호';

COMMENT ON COLUMN "CATEGORY"."CATEGORY_NM" IS '카테고리명';

COMMENT ON COLUMN "CATEGORY"."CATEGORY_IMG" IS '카테고리 이미지';

CREATE TABLE "SIGNUP" (
	"SIGNUP_NO"	NUMBER		NOT NULL,
	"COMMUNITY_NO"	NUMBER		NOT NULL,
	"SIGNUP_ST"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "SIGNUP"."SIGNUP_NO" IS '글 번호';

COMMENT ON COLUMN "SIGNUP"."COMMUNITY_NO" IS '모임 번호';

COMMENT ON COLUMN "SIGNUP"."SIGNUP_ST" IS '글 상태(정상N, 삭제Y)';

COMMENT ON COLUMN "SIGNUP"."CREATE_DT" IS '글 작성일';

CREATE TABLE "GET_TOGETHER" (
	"COMMUNITY_NO"	NUMBER		NOT NULL,
	"COMMUNITY_EVENT"	VARCHAR2(4000)		NULL,
	"COMMUNITY_DT"	DATE		NULL,
	"LIMITED_MEMBER"	NUMBER		NULL,
	"REVIEW"	VARCHAR2(4000)		NULL,
	"REVIEW_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "GET_TOGETHER"."COMMUNITY_NO" IS '모임 번호';

COMMENT ON COLUMN "GET_TOGETHER"."COMMUNITY_EVENT" IS '모임 정모 설명';

COMMENT ON COLUMN "GET_TOGETHER"."COMMUNITY_DT" IS '모임 일정';

COMMENT ON COLUMN "GET_TOGETHER"."LIMITED_MEMBER" IS '정모 제한인원';

COMMENT ON COLUMN "GET_TOGETHER"."REVIEW" IS '정모 후기';

COMMENT ON COLUMN "GET_TOGETHER"."REVIEW_FL" IS '후기 상태(Y:후기삭제, N:후기유지)';



-- 회원가입
-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO;

INSERT INTO MEMBER
		VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user01', 'pass01'
		, '유저일' , 'f' , TO_DATE('2014-01-01', 'YYYY-MM-DD'), '01011110000', '유저닉', DEFAULT, DEFAULT, '한국');

SELECT * FROM MEMBER;



-- 게시글 목록
-- 시퀀스 생성
CREATE SEQUENCE SEQ_COMMUNITY_NO;
BEGIN
   FOR I IN 1..30 LOOP
      INSERT INTO COMMUNITY 
      VALUES( SEQ_COMMUNITY_NO.NEXTVAL,
              SEQ_COMMUNITY_NO.CURRVAL || '번째 모임',
			  '이미지',
              SEQ_COMMUNITY_NO.CURRVAL || '번째 게시글 정보',
              SEQ_COMMUNITY_NO.CURRVAL || '번째 게시글 내용',
              SEQ_COMMUNITY_NO.CURRVAL || '지역',
              SEQ_COMMUNITY_NO.CURRVAL || 2,

              DEFAULT, DEFAULT, SEQ_COMMUNITY_NO.CURRVAL || '공지', 8
      );
   END LOOP;
END;
/

 INSERT INTO COMMUNITY 
      VALUES( SEQ_COMMUNITY_NO.NEXTVAL, SEQ_COMMUNITY_NO.CURRVAL || '번째 모임', '이미지', '정보', '내용', '지역', 1, DEFAULT, DEFAULT, '공지', 1);

SELECT * FROM COMMUNITY;
ALTER TABLE MEMBER MODIFY (MEMBER_PW VARCHAR2(2000)); 
CREATE TABLE "COMMUNITY" (
	"COMMUNITY_NO"	NUMBER		NOT NULL,
	"COMMUNITY_NM"	VARCHAR2(50)		NOT NULL,
	"COMMUNITY_IMG"	VARCHAR2(500)		NOT NULL,
	"COMMUNITY_INFO"	VARCHAR2(1000)		NOT NULL,
	"COMMUNITY_DETAIL"	VARCHAR2(4000)		NOT NULL,
	"COMMUNITY_AREA"	VARCHAR2(200)		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"COMMUNITY_ADMIN"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"COMMUNITY_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"COMMUNITY_NOTICE"	VARCHAR2(4000)		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL
);

-- 전체 게시글 수 조회
SELECT COUNT(*) FROM COMMUNITY
		WHERE COMMUNITY_FL = 'N';

위치, 모임명, 카테고리명, 인원수, 찜한수

-- 일정한 범위의 목록 조회
SELECT * FROM(
		   SELECT ROWNUM RNUM, A.* FROM(
		      SELECT BOARD_NO, BOARD_TITLE, MEMBER_NICK, 
		         TO_CHAR( CREATE_DT, 'YYYY-MM-DD' ) AS CREATE_DT, 
		         READ_COUNT ,
		         (SELECT IMG_RENAME FROM BOARD_IMG
		          WHERE IMG_LEVEL = 0
		          AND BOARD_IMG.BOARD_NO = BOARD.BOARD_NO) THUMBNAIL
		          
		      FROM BOARD
		      JOIN MEMBER USING(MEMBER_NO)
		      WHERE BOARD_CD = ?
		      AND BOARD_ST = 'N'
		      ORDER BY BOARD_NO DESC
		   ) A
		)
		WHERE RNUM BETWEEN ? AND ?;
-- 관심모임 삽입
INSERT INTO PICK
      VALUES(1, 42);

SELECT * FROM PICK;

-- 모임회원 삽입
SELECT * FROM COMMUNITY;

INSERT INTO COMMUNITY_MEMBER
	VALUES(6, 42, DEFAULT, DEFAULT);

-- 카테고리 삽입
INSERT INTO CATEGORY
	VALUES(8, '취미활동', 8);



-- 관심 모임 체크 수
SELECT COUNT(*) FROM PICK WHERE COMMUNITY_NO = 1;

-- 인원수
SELECT COUNT(*) FROM COMMUNITY_MEMBER;

-- 카테고리
SELECT * FROM CATEGORY;


-- 게시글 조회~~~
(SELECT IMG_RENAME FROM BOARD_IMG
		          WHERE IMG_LEVEL = 0
		          AND BOARD_IMG.BOARD_NO = BOARD.BOARD_NO) THUMBNAIL;

SELECT COMMUNITY_AREA, COMMUNITY_NO, CATEGORY_NM, 
	(SELECT COUNT(*) FROM PICK WHERE COMMUNITY.COMMUNITY_NO = PICK.COMMUNITY_NO) PICK, 
	(SELECT COUNT(*) FROM COMMUNITY_MEMBER WHERE COMMUNITY.COMMUNITY_NO = COMMUNITY_MEMBER.COMMUNITY_NO) COMMUNITY_MEMBER
FROM COMMUNITY
JOIN CATEGORY USING(CATEGORY_NO);

SELECT COMMUNITY_AREA, COMMUNITY_NM, CATEGORY_NM, (SELECT COUNT(*) FROM PICK WHERE COMMUNITY_NO = 1) PICK,
       (SELECT COUNT(*) FROM COMMUNITY_MEMBER WHERE COMMUNITY_NO = 1) COMMUNITY_MEMBER
FROM DUAL
JOIN CATEGORY USING(CATEGORY_NO);
-- 관심모임 수
SELECT COUNT(*) FROM PICK;

-- 게시글 목록조회 페이지
SELECT * FROM(
		   SELECT ROWNUM RNUM, A.* FROM(
		      SELECT COMMUNITY_AREA, COMMUNITY_NO, COMMUNITY_NM, CATEGORY_NM, 
	(SELECT COUNT(*) FROM PICK WHERE COMMUNITY_NO = 1) PICK, 
	(SELECT COUNT(*) FROM COMMUNITY_MEMBER WHERE COMMUNITY_NO = 1) COMMUNITY_MEMBER
				FROM COMMUNITY
				JOIN CATEGORY USING(CATEGORY_NO)
				WHERE COMMUNITY_FL = 'N'
		      ORDER BY COMMUNITY_NO DESC
		   ) A
		)
WHERE RNUM BETWEEN 6 AND 10;


-- 게시글 목록조회 페이지(진짜)
SELECT * FROM(
		   SELECT ROWNUM RNUM, A.* FROM(
		      SELECT COMMUNITY_AREA, COMMUNITY_NO, CATEGORY_NM, 
	(SELECT COUNT(*) FROM PICK WHERE COMMUNITY.COMMUNITY_NO = PICK.COMMUNITY_NO) PICK, 
	(SELECT COUNT(*) FROM COMMUNITY_MEMBER WHERE COMMUNITY.COMMUNITY_NO = COMMUNITY_MEMBER.COMMUNITY_NO) COMMUNITY_MEMBER
FROM COMMUNITY
JOIN CATEGORY USING(CATEGORY_NO)
				WHERE COMMUNITY_FL = 'N'
		      ORDER BY COMMUNITY_NO DESC
		   ) A
		)
WHERE RNUM BETWEEN 6 AND 10;

-- 이미지 테이블 생성
-- CREATE TABLE COMMUNITY_IMG(
--    IMG_NO NUMBER PRIMARY KEY,
--    IMG_RENAME VARCHAR2(500) NOT NULL,
--    IMG_ORIGINAL VARCHAR2(500) NOT NULL,
--    IMG_LEVEL NUMBER NOT NULL,
--    COMMUNITY_NO NUMBER REFERENCES COMMUNITY
-- );

-- COMMENT ON COLUMN COMMUNITY_IMG.IMG_NO IS '이미지 번호';
-- COMMENT ON COLUMN COMMUNITY.IMG_RENAME IS '이미지 저장 경로 + 변경명';
-- COMMENT ON COLUMN COMMUNITY.IMG_ORIGINAL IS '이미지 원본명';
-- COMMENT ON COLUMN COMMUNITYG.IMG_LEVEL IS '이미지 위치 지정 번호';
-- COMMENT ON COLUMN COMMUNITY.BOARD_NO IS '게시글 번호';


-- -- 이미지 번호 시퀀스 생성
-- CREATE SEQUENCE SEQ_IMG_NO NOCACHE;