CREATE TABLE "MEMBER" (
    "MEMBER_NO" NUMBER      NOT NULL,
    "MEMBER_ID" VARCHAR2(50)        NOT NULL,
    "MEMBER_PW" VARCHAR2(30)        NOT NULL,
    "MEMBER_NM" VARCHAR2(20)        NOT NULL,
    "MEMBER_GENDER" CHAR(1)     NOT NULL,
    "MEMBER_BIRTH"  DATE        NOT NULL,
    "MEMBER_PHONE"  VARCHAR2(20)        NOT NULL,
    "MEMBER_NICK"   VARCHAR2(20)        NOT NULL,
    "SECESSION_FL"  CHAR(1) DEFAULT 'N' NOT NULL,
    "PROFILE_IMG"   VARCHAR2(500)       NOT NULL,
    "MEMBER_LIVE"   VARCHAR2(100)       NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호(시퀀스)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 이메일(아이디)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NM" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_GENDER" IS '회원 성별';

COMMENT ON COLUMN "MEMBER"."MEMBER_BIRTH" IS '회원 생년월일';

COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS '회원 휴대폰번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICK" IS '회원 닉네임';

COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '탈퇴여부(Y:탈퇴, N:미탈퇴)';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '회원 프로필 이미지';

COMMENT ON COLUMN "MEMBER"."MEMBER_LIVE" IS '회원 지역';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
    "MEMBER_NO"
);

CREATE SEQUENCE SEQ_MEMBER_NO;

INSERT INTO MEMBER 
VALUES(SEQ_MEMBER_NO.NEXTVAL,'user01@kh.or.kr', 'pass01!', '유저일', 'M', SYSDATE, '01012345678', '유저일', DEFAULT, NULL, '서울');

COMMIT;

ALTER TABLE MEMBER DROP CONSTRAINT SYS_C008578;

DELETE FROM "MEMBER" WHERE MEMBER_NO =2;

SELECT * FROM MEMBER;

SELECT MEMBER_NO, MEMBER_ID,MEMBER_PW, MEMBER_NM, MEMBER_GENDER, 
TO_CHAR(MEMBER_BIRTH, 'YYYY-MM-DD') AS MEMBER_BIRTH, MEMBER_PHONE, MEMBER_NICK, PROFILE_IMG, MEMBER_LIVE 
FROM MEMBER
WHERE MEMBER_ID = ?
AND MEMBER_PW = ?
AND SECESSION_FL ='N';




INSERT INTO MEMBER 
VALUES(SEQ_MEMBER_NO.NEXTVAL,'user02@kh.or.kr', 'pass02@', '유저이', 'M', SYSDATE, '01023455678', '호랑이', DEFAULT, NULL, '서울');

COMMIT;


SELECT COUNT(*) FROM MEMBER
        WHERE MEMBER_NICK = '유저일'
        AND SECESSION_FL ='N';
        
SELECT MEMBER_NICK FROM MEMBER;


INSERT INTO MEMBER 
VALUES(SEQ_MEMBER_NO.NEXTVAL,'user03@kh.or.kr', 'pass03#', '유저삼', 'M', SYSDATE, '01023455678', '파국이다', DEFAULT, NULL, '서울');

COMMIT;

ALTER TABLE MEMBER MODIFY(MEMBER_PW VARCHAR2(100));

UPDATE MEMBER 
SET MEMBER_PW = 'k1AvTlLTYv9GAKzy4/6ydEuIS11oKBro81C7Wzq5QkoL3wGx1Y0gWas5ICgOdyvDYDzzb2OESO/fYO4OyQNojw=='
WHERE MEMBER_ID = 'user03@kh.or.kr';

COMMIT;

-- 인증 테이블 생성
 -- 한 이메일로 발급 받은 인증번호가 계속 업데이트
CREATE TABLE CERTIFICATION (
   EMAIL VARCHAR2(50) PRIMARY KEY,
   C_NUMBER CHAR(6) NOT NULL,
   ISSUE_DT DATE DEFAULT SYSDATE
);

-- user01@kh.or.kr   123456   

SELECT EMAIL, C_NUMBER,
   TO_CHAR(ISSUE_DT, 'YYYY-MM-DD HH24:MI:SS')
 FROM CERTIFICATION;



-- 일정 시간이 지난 후를 조회하는 방법
--> 인증번호 발급시간 + 5분 == 발급 받은지 5분이 지남 == 인증번호 만료
-- (INTERVAL '1' HOUR | MINUTE | SECOND)
SELECT TO_CHAR(SYSDATE + (INTERVAL '5' MINUTE), 'YYYY-MM-DD HH24:MI:SS') 
FROM DUAL;

-- 발급 시간 + 5 분 < 현재 시간 == 만료
-- 17:03 + 5분 == 17:08      <  17:11  

-- 발급 시간 + 5 분 > 현재 시간 == 인증 가능 시간
-- 17:03 + 5분 == 17:08    >  17:06  


-- NVL( A , B ) : A가 NULL 이면 B를 반환

SELECT * FROM CERTIFICATION;

-- 조건절이 TRUE이면 '1' , 아니면 NULL  조회
SELECT '1' FROM CERTIFICATION
WHERE 1 = 0;


SELECT 
   -- 이메일, 인증번호가 일치하는 행이 있는지를 찾음 -> 있으면 1, 없으면 NULL
   --> 1이면 THEN 구문 수행  , NULL이면 ELSE 수행
   CASE WHEN (SELECT '1' FROM CERTIFICATION
               WHERE EMAIL = 'knbdh9782@naver.com'
               AND C_NUMBER = '6jJZWz')  = 1
   
      THEN NVL( (SELECT '1' FROM CERTIFICATION
                  WHERE EMAIL = 'knbdh9782@naver.com'
                  AND ISSUE_DT + (INTERVAL '5' MINUTE) >= SYSDATE) , '2') 
                  
      ELSE '3'  
   END          
FROM DUAL;
