CREATE TABLE "MEMBER" (
    "MEMBER_NO" NUMBER      NOT NULL,
    "MEMBER_ID" VARCHAR2(50)        NOT NULL,
    "MEMBER_PW" VARCHAR2(30)        NOT NULL,
    "MEMBER_NM" VARCHAR2(20)        NOT NULL,
    "MEMBER_GENDER" CHAR(1)     NOT NULL,
    "MEMBER_BIRTH"  DATE        NOT NULL,
    "MEMBER_PHONE"  VARCHAR2(20)        NOT NULL,
    "MEMBER_NICK"   VARCHAR2(20)        NOT NULL,
    "SECESSION_FL"  CHAR(1) DEFAULT 'N' NOT NULL,
    "PROFILE_IMG"   VARCHAR2(500)       NOT NULL,
    "MEMBER_LIVE"   VARCHAR2(100)       NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호(시퀀스)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 이메일(아이디)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NM" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_GENDER" IS '회원 성별';

COMMENT ON COLUMN "MEMBER"."MEMBER_BIRTH" IS '회원 생년월일';

COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS '회원 휴대폰번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICK" IS '회원 닉네임';

COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '탈퇴여부(Y:탈퇴, N:미탈퇴)';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '회원 프로필 이미지';

COMMENT ON COLUMN "MEMBER"."MEMBER_LIVE" IS '회원 지역';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
    "MEMBER_NO"
);

CREATE SEQUENCE SEQ_MEMBER_NO;

INSERT INTO MEMBER 
VALUES(SEQ_MEMBER_NO.NEXTVAL,'user01@kh.or.kr', 'pass01!', '유저일', 'M', SYSDATE, '01012345678', '유저일', DEFAULT, NULL, '서울');

COMMIT;

ALTER TABLE MEMBER DROP CONSTRAINT SYS_C008578;

DELETE FROM "MEMBER" WHERE MEMBER_NO =2;

SELECT * FROM MEMBER;

SELECT MEMBER_NO, MEMBER_ID,MEMBER_PW, MEMBER_NM, MEMBER_GENDER, 
TO_CHAR(MEMBER_BIRTH, 'YYYY-MM-DD') AS MEMBER_BIRTH, MEMBER_PHONE, MEMBER_NICK, PROFILE_IMG, MEMBER_LIVE 
FROM MEMBER
WHERE MEMBER_ID = ?
AND MEMBER_PW = ?
AND SECESSION_FL ='N';




INSERT INTO MEMBER 
VALUES(SEQ_MEMBER_NO.NEXTVAL,'user02@kh.or.kr', 'pass02@', '유저이', 'M', SYSDATE, '01023455678', '호랑이', DEFAULT, NULL, '서울');

COMMIT;
